### ISSUE TITLE
Outdated python versions on PyPI (and in wheel metadata)

### ISSUE THREAD

**Issue by APCBoston** [Instagram/LibCST#1079]
Libcst's project page at https://pypi.org/project/libcst/ states in a banner that it can parse up to Python 3.10, and in the description states "LibCST parses Python 3.0 -> 3.11 ...", though it appears that 3.12 is now supported.  Additionally, the language metadata on PyPI lists only up to Python3.11.

The x64-manylinux wheel metadata also reflects these issues.

This may be related, at least in part, to the fact that the PyPI job in Github Actions appears to have been consistently failing for the last two months (https://github.com/Instagram/LibCST/actions/workflows/pypi_upload.yml), blocking a push that would have updated `readme.rst` there.

**Comment by zsol** [comment]
It's because the readme and project metadata have been updated since we've made a pypi release: https://github.com/Instagram/LibCST/commit/19c2862ea3d709ab94184a4ca2875d337936d800 and https://github.com/Instagram/LibCST/commit/88d0b36cdd99c14cdf70784d292cfa3b5032782e

These will automatically be fixed with the next release (now that I've fixed the `pypi_upload` job), as the [test.pypi.org](https://test.pypi.org/project/libcst/1.1.1.dev18/) page shows

**Comment by APCBoston** [comment]
@zsol thanks!
