### ISSUE TITLE
3.8 Support

### ISSUE THREAD

**Issue by cooperlees** [Instagram/LibCST#122]
I have a test runner that uses Pyre as an option for type-checking, [ptr](https://github.com/facebookincubator/ptr). I put up a diff to move CI to start using official 3.8 for test running on travis and this results in the expected ValueError:
```
raise ValueError(
ValueError: LibCST can only parse code using one of the following versions of Python's grammar: 3.5, 3.6, 3.7. More versions may be supported by future releases.
```
- CI Job: https://travis-ci.com/facebookincubator/ptr/jobs/247724096

What is there an expected timeframe for 3.8 support? I will have the tool not run `pyre` for now in >=3.8. What's the thoughts on possibly adding a section to the README explaining the 3.8 support plans with 3.8 being an official version now?

**Comment by DragonMinded** [comment]
This is on my list of TODOs underneath some deprecation tasks and continued work on `matchers` API. I don't have any real timeline for supporting this but I can certainly bump priority since there is demand for it.

Support for 3.8 comes in two flavors, however: First is the ability to execute LibCST on 3.8 code. This *should* be available, but you're running into a snag with LibCST's automatic detection of versions. If a python version isn't supplied to the parser, it assumes the version that you're running and since we can't parse 3.8 yet, it fails. Fixing that is possible if you want to hardcode the parser version (which we do in some parser tests). The second flavor is arguably the only useful version, which is the ability to parse 3.8 code, regardless of the currently running python. That's what I assume this feature request is for, and what I can't give an official timeline on yet.

Can you provide your own timeline and such so I can tell how urgently this needs to get addressed?

**Comment by cooperlees** [comment]
That's fine. Long as it's planned :) I have disabled it in ptr for >= 3.8 for now. My PR is linked above to do this. I'll keep an eye and when this is closed I'll undo the disable :)

**Comment by DragonMinded** [comment]
Not sure why mentioning this in a comment auto-closed on merge, but this is not finished.

**Comment by bgw** [comment]
> Not sure why mentioning this in a comment auto-closed on merge

:laughing: 

![Screenshot from 2019-10-28 17-20-48](https://user-images.githubusercontent.com/180404/67727636-6b814780-f9a7-11e9-9f7c-e0b249dcc4f1.png)

Certain keywords, like "closes" and "fixes" can be used to auto-close issues, however github isn't context sensitive. https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by dseevr** [comment]
Is this issue being looked at/considered for development?  We've had to stop using pyre entirely because it's [blocked on this issue](https://github.com/facebook/pyre-check/issues/213).

**Comment by bgw** [comment]
Hey @dseevr, that sucks. Unfortunately, Thanksgiving is approaching, and a lot of people are on vacation, so we might not be able to get back to you until next week.

**Comment by jimmylai** [comment]
@dseevr, yes, we've started the work of Python 3.8 supports and some preliminary support was published in LibCST 0.2.3
https://github.com/Instagram/LibCST/blob/master/CHANGELOG.md

**Comment by DragonMinded** [comment]
We don't have plans for complete 3.8 support for the rest of the year. However, the preliminary support pushed on the 11th of last month should be enough to unblock Pyre (and it has unblocked sister teams). Pyre needs to upgrade their dependency to 0.2.4.

**Comment by DragonMinded** [comment]
Once #213 and #209 are in, we will fully support Python 3.8, both in executing LibCST and in parsing/generating code. I plan to make a release sometime this week.

**Comment by DragonMinded** [comment]
Oops, forgot to close this. This is live now.
