### ISSUE TITLE
Parameters for metadata providers

### ISSUE THREAD

**Issue by willcrichton** [Instagram/LibCST#267]
In my application, I have information about whether particular line numbers were executed. I would like to use a metadata provider to turn this information into AST node-level annotations. However, this requires my `IsNodeExecutedProvider` to be parameterized by information external to the AST. As far as I can tell, neither the `wrapper.resolve` nor `METADATA_DEPENDENCIES` APIs allow metadata providers to take parameters, e.g. by overriding `__init__`. 

Is there a way to do this that I have not found, or is this otherwise on the roadmap?

**Comment by jimmylai** [comment]
MetadataProvider cannot take parameter since we don't see the need from common use cases.
What kind of information you want to parameterize? Can you just use a CSTVisitor take custom parameters? Or can you use the `Mapping` returned by `MetadataWrapper.resolve()` and then combine the information you need?
https://libcst.readthedocs.io/en/latest/metadata.html#libcst.metadata.MetadataWrapper

**Comment by willcrichton** [comment]
Ok, I'll work around this then. Thanks!
