### ISSUE TITLE
[scope analysis] References attached to the wrong scope

### ISSUE THREAD

**Issue by zsol** [Instagram/LibCST#326]
Consider this example:
```
from a import b
class X:
    @b
    def b(self):
        pass
```
In this case `@b` refers to the `b` imported in the global scope, but `ScopeProvider` attaches the access to the method definition instead. This means the imported `b` has 0 references (and as a consequence, gets cleaned up by `RemoveImportsVisitor`).

**Comment by jimmylai** [comment]
There are two `b` `Assignment` definitions: import in `GlobalScope` and function in `ClassScope`.
The `Access` `b` is in `ClassScope`.
The reason it's associated with the `Assignment` in `ClassScope` rather than `GlobalScope` is because the access inference is at the end of scope analysis.
https://github.com/Instagram/LibCST/blob/c023fa7c4caff3fd2b3946080f9a58b539b10363/libcst/metadata/scope_provider.py#L824

By the inference time, each access tries to find an `Assignment` from the current scope or its parent to associate with and we cannot tell the `Assignment` `b` in `ClassScope` is not usable due to it is defined later than the access.
What we can do here is to record the statement index number to each `Assignment` and `Access`. When inferring the access to assignment in the same scope, we only associate them if and only if the access has a statement index larger than the assignment. The statement index number can be defined as a `Tuple` to include the index number for each scope level. E.g. the imported `b` has `(0,)`, the decorator access `b` and function `b` both has `(1, 0)`.
`(1, 0)` is not greater than `(1,0)`, and it's greater than `(0,)`. So we will assign the decorator to the imported `b`.

**Comment by zsol** [comment]
Another example:
```
from a import b

class X:
   x: Any = b  # this b should be attached to the b in GlobalScope
   b: Any = ""
```
