### ISSUE TITLE
Conversion to ast asts

### ISSUE THREAD

**Issue by KOLANICH** [Instagram/LibCST#459]
AST is blessed and in the standard lib, so it is a standard used by some tools, so it'd be nice to be able to convert from LibCST AST to ast AST.

**Comment by thatch** [comment]
It would be very difficult to incrementally build an ast since it's not 1:1 with the cst.  Perhaps you can do something like

```
a = ast.parse(mod.code)
```

but this is limited to what can be represented in the current version of python, which libcst is not.  typed_ast gets you a little more compatibility there, but has other issues.

I think that snippet is simple enough that you can do it in your application?

**Comment by KOLANICH** [comment]
>but this is limited to what can be represented in the current version of python

In fact I used it exactly to decouple from version of current interpreter.

> typed_ast gets you a little more compatibility there, but has other issues.

Thanks for the info!

**Comment by user202729** [comment]
I just come across this issue. Of course `ast.parse` can convert a CST into an AST, but the disadvantage is that the original line/column number information is lost.

This would be important for something that wants to execute a modified source code, but keeps the line/column number information of the original source code for accurate error reporting. (Some libraries such as SageMath or IPython magic does this.)

Is this possible at the moment? (I think if libcst keeps the line/column information of each node it should not be too difficult to match which character in the old source code correspond with which character in the new one, which would allow back-translating the AST's line/column numbers with reasonable accuracy.)
