### ISSUE TITLE
Allow grouping parens around with...as for 3.9

### ISSUE THREAD

**Issue by thatch** [Instagram/LibCST#490]
Reported in https://github.com/Zac-HD/shed/issues/18

The discussion on https://github.com/psf/black/issues/1948 seems to imply that this is due to a parser change, and not an actual change in the grammar.  If so that's a bit unfortunate, and I wonder if there are other cases that allow parens now that didn't before.

@Zac-HD do you have any other examples that would be helpful here?

(While making edits in this area, should fix the validation issue #439)

**Comment by Zac-HD** [comment]
Per [PEP-617](https://www.python.org/dev/peps/pep-0617/#some-rules-are-not-actually-ll-1), this actually is a change to the grammar, which was previously impossible because the old LL(1) parser couldn't recognise it without *even more* tokeniser hacks.  It had been desired as "obviously the right thing to do" for years, but if it can't be parsed...

AFIACT this is the only such change due to the new parser; relaxed grammar for decorators #486 is also new in 3.9 but was separately motivated and would have been possible in the old parser too.
