### ISSUE TITLE
Documentation graphs are not rendered

### ISSUE THREAD

**Issue by abitrolly** [Instagram/LibCST#725]
https://libcst.readthedocs.io/en/latest/why_libcst.html

Diagrams look like this.

![image](https://user-images.githubusercontent.com/8781107/182094555-4f9a5067-9962-4daa-8cc5-36a85107b68c.png)

**Comment by MapleCCC** [comment]
I can confirm that I see the same problem on my browser.

By the way, since the last document build is more than 5 months ago, maybe make a fresh document build now is a good idea.

**Comment by MapleCCC** [comment]
I further investigated the problem. Turn out this bug is related to how the new builder image provided by readthedocs doesn't have the `graphviz-dev` package pre-installed any more, as elaborated in upstream readthedocs issues [8672](https://github.com/readthedocs/readthedocs.org/issues/8672) and [8800](https://github.com/readthedocs/readthedocs.org/issues/8800).

The related readthedocs FAQ entry is seen in ["My documentation requires additional dependencies"](https://docs.readthedocs.io/en/stable/faq.html?highlight=C%20libraries#my-documentation-requires-additional-dependencies).

The solution, as elaborated on the upstream issues and document, is to set the configuration option [`build.apt_packages`](https://docs.readthedocs.io/en/stable/config-file/v2.html#id18) in `.readthedocs.yaml` to install the `graphviz` package before document build.

**Comment by MapleCCC** [comment]
A PR #751 has been opened to fix this issue.
