### ISSUE TITLE
Immutable module attribute on libcst visitor / best way to use code_for_node

### ISSUE THREAD

**Issue by zhammer** [Instagram/LibCST#76]
Seems like a flow for me when debugging transformers will be adding a new attribute to a visitor/transformer to capture the visited module as `self.module`. i'd do this in the `visit_Module` handler so that I can later do `print(self.module.code_for_node(current_node)`.

is this in sync with how `code_for_node` is being used internally at instagram? this gets a bit confusing if the original module is mutated during tree traversing so that code for node on an `updated_node` may not be totally accurate. (though this is where my _full_ understanding of the visitor pattern gets fuzzier).

just curious how y'all use `code_for_node` in debugging workflows.

**Comment by DragonMinded** [comment]
We have another layer that I haven't had the time to get open sourced yet which provides some convenience accessors. Among other things, it handles the command-line for running a transform across multiple files (which I think I remember seeing you had to rebuild yourself unfortunately). Included in that infrastructure is a context that is passed through to the transform which includes the current file being modified, a place to put warnings that might be printed to the console, and a reference to a pre-computed metadata wrapper which includes the module reference. We wrap all that so you can do `self.module` references on the transform, effectively allowing you to access `code_for_node` to debug and `config_for_parsing` to make template-based generation from `parse_statement` and `parse_expression` easier.

Note that the module itself isn't modified until leave_Module is returned. Due to the immutable nature of the tree, the only thing that can change during traversal is a `Module`'s traversable children. That means the attributes on a `Module` that affect `code_for_node` and `config_for_parsing` can only be modified in that `leave_Module` method itself. Hence, it is safe to call `code_for_node` any time during traversal and be assured that it is correct.

**Comment by zhammer** [comment]
awesome :). these are all features i've wanted to build out or have done quick passes at when using libcst.

**Comment by DragonMinded** [comment]
I'm not sure anything I wrote here qualifies for a documentation change (except for maybe to document upcoming features we intend to open-source) so I'm going to close it. If you have any more questions, or a followup on this one, feel free to reopen or open a new issue!
