### ISSUE TITLE
Parsing does not raise error for code assigning to a function call

### ISSUE THREAD

**Issue by DRMacIver** [Instagram/LibCST#916]
LibCST will happily parse the following code:

```
import libcst
libcst.parse_statement('max() = 1')
```

However this is a syntax error, as you can't assign to function calls, and ideally would be raised as such.

(Tested on libcst 0.4.9)

**Comment by jakkdl** [comment]
So, I'm looking at whether to place this validation in `BaseAssignTargetExpression`, `AssignTarget`, and/or `Assign`/`AnnAssign`/`AugAssign`.

https://github.com/Instagram/LibCST/blob/ea19578293f8bc20d51d3b0b3f51c7771ed52944/libcst/_nodes/expression.py#L286-L301
since 3.9 the python grammar does define the valid assignment targets
```
 assignment:
    | NAME ':' expression ['=' annotated_rhs ] 
    | ('(' single_target ')' 
         | single_subscript_attribute_target) ':' expression ['=' annotated_rhs ] 
    | (star_targets '=' )+ (yield_expr | star_expressions) !'=' [TYPE_COMMENT] 
    | single_target augassign ~ (yield_expr | star_expressions) 
```
so I thought I'd add a `_validate` to `BaseAssignTargetExpression` that checks whether it's a `Name`, `Subscript` or `StarredElement`. But then I noticed that a *lot* of other classes inherits from it, including `Name`, `Annotation`, `Attribute` - which all quickly starts breaking if I restrict what `BaseAssignTargetExpression` can be. Is there a reason why all of these don't just inherit from `BaseExpression`, or can I change them to do so? Or should I place the validation in `AssignTarget` instead?

**Comment by jakkdl** [comment]
@zsol any thoughts on the above?

**Comment by zsol** [comment]
The native parser correctly raises a syntax error here. So to work around you can set the `LIBCST_PARSER_TYPE` environment variable to `native` before calling libcst, or wait for the next release which will have this behavior by default due to #929

**Comment by jakkdl** [comment]
Oh, I totally thought I tested it with `native` - but apparently not. Sweet!

**Comment by zsol** [comment]
Gonna close this out as native parser is enabled by default in 1.0.0
